version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: burgerdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_NAME: burgerdb
      DB_USER: myuser
      DB_PASS: mypassword
      DB_HOST: postgres
      DB_PORT: 5432

  frontend:
    build: ./Frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  pgdata:
