apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: burger-app
data:
  POSTGRES_DB: "burgerdb"
  POSTGRES_USER: "myuser"
  POSTGRES_HOST: "localhost"   # Optional: can be used in deployments
  POSTGRES_PORT: "5432"        # Optional
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: burger-app
type: Opaque
data:
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==   # base64 of 'mypassword'
